Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-03, with the labels that each got.

#74 increase readiness probe timeout
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/deploymentconfig.yaml
  stable/database/templates/statefulset.yaml
Labels: enhancement

#75 Add SCC for NuoDB Helm in OpenShift
  .travis.yml
  deploy/nuodb-scc.yaml
  docs/ManuallyDisableTHP.md
  scripts/ci/install_deps.sh
  stable/README.md
  stable/admin/README.md
  stable/database/README.md
  stable/database/values.yaml
  stable/restore/README.md
  test/minikube/minikube_base_admin_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_base_thp_test.go
  test/minikube/minikube_long_admin_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/open_shift_utilities.go
  test/testlib/tls.go
Labels: enhancement, feature

#77 Autoconfigure role and service account
  stable/admin/README.md
  stable/admin/templates/role.yaml
  stable/admin/templates/rolebinding.yaml
  stable/admin/templates/serviceaccount.yaml
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/cronjob.yaml
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/deploymentconfig.yaml
  stable/database/templates/job.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
  stable/restore/templates/job.yaml
  test/integration/template_database_test.go
  test/integration/template_resources_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_tls_admin_test.go
Labels: enhancement, feature

#51 Add cluster domain support
  incubator/backup/templates/_helpers.tpl
  incubator/backup/templates/cronjob.yaml
  incubator/backup/values.yaml
  stable/admin/README.md
  stable/admin/templates/_helpers.tpl
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/_helpers.tpl
  stable/database/values.yaml
  stable/restore/templates/_helpers.tpl
  stable/restore/values.yaml
  test/integration/template_admin_test.go
  test/minikube/minikube_test_test.go
  test/testlib/nuodb_database_utilities.go
Labels: enhancement

#81 skip doc builds
  .travis.yml
Labels: meta

#79 Jleslie/readme upd 03 12
  README.md
  incubator/backup/README.md
  incubator/demo-ycsb/README.md
  incubator/monitoring-influx/README.md
  incubator/monitoring-insights/README.md
  stable/README.md
  stable/admin/README.md
  stable/database/README.md
  stable/restore/README.md
  stable/storage-class/README.md
  stable/transparent-hugepage/README.md
Labels: documentation

#66 Remove OpenShift specific TE DeploymentConfig
  incubator/monitoring-influx/README.md
  incubator/monitoring-influx/templates/deployment.yaml
  incubator/monitoring-influx/templates/deploymentconfig.yaml
  incubator/monitoring-influx/values.yaml
  incubator/monitoring-insights/README.md
  incubator/monitoring-insights/templates/deployment.yaml
  incubator/monitoring-insights/values.yaml
  stable/database/README.md
  stable/database/templates/deployment.yaml
  stable/database/templates/deploymentconfig.yaml
  stable/database/values.yaml
  test/integration/template_database_test.go
  test/integration/template_resources_test.go
Labels: removed
