Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-02, with the labels that each got.

#57 allow a user to override admin services suffixes
  stable/admin/README.md
  stable/admin/templates/service-clusterip.yaml
  stable/admin/templates/service.yaml
  stable/admin/values.yaml
Labels: enhancement

#65 Enable eviction of unresponsive processes and bump version back up to 4.0.4
  .travis.yml
  incubator/backup/values.yaml
  incubator/monitoring-influx/values.yaml
  incubator/monitoring-insights/values.yaml
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/values.yaml
  stable/restore/values.yaml
  test/integration/template_admin_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/testlib/nuodb_database_utilities.go
Labels: bug, meta, versioning

#69 Fix kill process test
  test/testlib/minikube_utilities.go
Labels: meta

#71 Change Gcloud Link
  README.md
  scripts/index
  scripts/index.html.erb
Labels: documentation
