Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-04, with the labels that each got.

#86 Add `describe statefulset` to admin startup tests
  test/testlib/nuodb_admin_utilities.go
Labels: meta

#87 Add test exercising domain resync
  test/minikube/minikube_domain_resync_test.go
  test/testlib/NuoDBArchive.go
  test/testlib/NuoDBProcess.go
  test/testlib/constants.go
Labels: meta

#88 fix print in upgrade test
  test/testlib/minikube_utilities.go
Labels: meta

#91 Archive location got moved - fix test link
  test/testlib/constants.go
Labels: meta

#93 Stop printing diagnose to stdout
  .travis.yml
Labels: meta

#94 Fix YCSB for non-cloud environments
  incubator/demo-ycsb/files/cloud.sh
  incubator/demo-ycsb/files/ycsb_gen.sh
  incubator/demo-ycsb/templates/configmap.yaml
  incubator/demo-ycsb/templates/replicationcontroller.yaml
  test/minikube/minikube_e2e_demo_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_ycsb_utilities.go
Labels: bug

#95 Add replicas helm template value to YCSB
  incubator/demo-ycsb/README.md
  incubator/demo-ycsb/templates/replicationcontroller.yaml
  incubator/demo-ycsb/values.yaml
  test/integration/template_ycsb_test.go
Labels: enhancement

#99 Remove obsolete charts from Incubator
  incubator/.gitignore
  incubator/backup/Chart.yaml
  incubator/backup/README.md
  incubator/backup/templates/NOTES.txt
  incubator/backup/templates/_helpers.tpl
  incubator/backup/templates/cronjob.yaml
  incubator/backup/values.yaml
  incubator/monitoring-influx/.helmignore
  incubator/monitoring-influx/Chart.yaml
  incubator/monitoring-influx/README.md
  incubator/monitoring-influx/files/dashboards/adhoc.json
  incubator/monitoring-influx/files/dashboards/communication.json
  incubator/monitoring-influx/files/dashboards/connections.json
  incubator/monitoring-influx/files/dashboards/cpu.json
  incubator/monitoring-influx/files/dashboards/dashboard.json
  incubator/monitoring-influx/files/dashboards/disk.json
  incubator/monitoring-influx/files/dashboards/memory.json
  incubator/monitoring-influx/files/dashboards/nuodb-overview.json
  incubator/monitoring-influx/files/dashboards/nuodb-summary.json
  incubator/monitoring-influx/files/dashboards/sql.json
  incubator/monitoring-influx/templates/NOTES.txt
  incubator/monitoring-influx/templates/_helpers.tpl
  incubator/monitoring-influx/templates/configmap.yaml
  incubator/monitoring-influx/templates/deployment.yaml
  incubator/monitoring-influx/templates/persistentvolumeclaim.yaml
  incubator/monitoring-influx/templates/pod.yaml
  incubator/monitoring-influx/templates/route.yaml
  incubator/monitoring-influx/templates/service.yaml
  incubator/monitoring-influx/values.yaml
  incubator/restore-copy/templates/job.yaml
Labels: removed

#100 Add test of membership resync based on Admin StatefulSet
  test/minikube/minikube_domain_resync_test.go
  test/testlib/nuodb_admin_utilities.go
Labels: meta

#105 Minor doc fix in YCSB
  incubator/demo-ycsb/README.md
Labels: documentation

#104 Fix Helm Operator Scorecard requirement of no empty blocks
  .travis.yml
  stable/admin/templates/configmap.yaml
  stable/database/templates/configmap.yaml
  test/integration/template_admin_test.go
  test/integration/template_database_test.go
Labels: bug

#102 Enable multi-admin tests to catch regressions
  scripts/ci/determine_and_run_tests.sh
  test/minikube/minikube_base_admin_test.go
  test/minikube/minikube_long_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/testlib/minikube_utilities.go
Labels: meta

#106 Remove memoryOption and replace it with resources.requests.memory
  samples/large.yaml
  samples/standard.yaml
  samples/tiny.yaml
  stable/database/README.md
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
  test/integration/template_resources_test.go
Labels: removed
