Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-01, with the labels that each got.

#50 Add TE/SM Log to the Unit Tests
  test/minikube/minikube_base_admin_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_tls_admin_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: enhancement, meta

#54 Downgrade NuoDB to 4.0.3
  .travis.yml
  incubator/backup/values.yaml
  incubator/monitoring-influx/values.yaml
  incubator/monitoring-insights/values.yaml
  stable/admin/values.yaml
  stable/database/values.yaml
  stable/restore/values.yaml
  test/minikube/minikube_rolling_upgrade_test.go
Labels: versioning

#55 Add option to dump cores if specific test fails
  .travis.yml
  test/minikube/minikube_base_database_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: enhancement, meta

#56 Minor improvements to the tests
  test/integration/database_marshall_test.go
  test/minikube/minikube_test_test.go
  test/testlib/NuoDBDatabase.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
Labels: enhancement, meta

#53 Home page updates to clarify the requirement for Helm version 2, 2.9 or greater
  README.md
Labels: documentation
