Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-12, with the labels that each got.

#167 Move Testing from TravisCI to CircleCI
  .circleci/config.yml
  .travis.yml
  README.md
  scripts/ci/install_deps.sh
Labels: meta

#169 Bump NuoDB Version to 4.0.8
  stable/admin/README.md
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/values.yaml
  stable/restore/README.md
  stable/restore/values.yaml
  test/minikube/minikube_rolling_upgrade_test.go
Labels: versioning

#171 Transparent Data Encryption HowTo document
  docs/HowtoTDE.md
Labels: documentation

#173 All journal backups fail while a full backup is running
  stable/database/files/nuobackup
Labels: bug

#172 Initial backup job in multicluster deployment fails
  stable/database/files/nuobackup
  stable/database/templates/job.yaml
Labels: bug
