Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-08, with the labels that each got.

#131 add support for DIAGNOSTIC teardown funcs.
  test/minikube/minikube_test_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
Labels: meta

#133 Add support for LoadBalancer specification via annotations in admin statefulset and TE deployment
  stable/admin/README.md
  stable/admin/templates/_helpers.tpl
  stable/admin/templates/role.yaml
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/_helpers.tpl
  stable/database/templates/deployment.yaml
  stable/database/values.yaml
  test/integration/template_admin_test.go
  test/integration/template_database_test.go
  test/minikube/minikube_domain_resync_test.go
  test/testlib/NuoDBKubeConfig.go
  test/testlib/NuoDBLoadBalancerConfig.go
  test/testlib/NuoDBLoadBalancerPolicy.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/open_shift_utilities.go
Labels: enhancement, feature

#135 Change database container names to "engine"
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/statefulset.yaml
Labels: enhancement

#136 Expose bootstrapServers value as Admin statefulset annotation
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  test/integration/template_admin_test.go
Labels: meta

#137 Add more diagnostics for TestKubernetesTLSRotation test
  .gitignore
  scripts/ci/install_deps.sh
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_test_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
  test/testlib/nuodb_ycsb_utilities.go
Labels: meta

#141 Add DaemonSets to list of NuoDB Kubernetes Aware Admin permissions
  stable/admin/templates/role.yaml
  test/testlib/NuoDBKubeConfig.go
Labels: enhancement

#144 Bump NuoDB version to 4.0.7
  stable/admin/values.yaml
  stable/database/values.yaml
  stable/restore/values.yaml
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/nuodb_admin_utilities.go
Labels: versioning

#145 Bump NuoDB version to 4.0.7 [2.4-dev branch]
  stable/admin/values.yaml
  stable/database/values.yaml
  stable/restore/values.yaml
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/nuodb_admin_utilities.go
Labels: versioning
