Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-09, with the labels that each got.

#146 Improve tests for OpenShift 4.5.7 CodeReadyContainers
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: meta

#142 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#148 Improve Upgrade/Enterprise Tests
  .travis.yml
  README.md
  scripts/ci/determine_and_run_tests.sh
  test/integration/template_admin_test.go
  test/integration/template_database_test.go
  test/integration/template_resources_test.go
  test/integration/template_storage_class_test.go
  test/integration/template_utilities.go
  test/integration/template_ycsb_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_crash_handling_test.go
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_e2e_demo_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
  test/testlib/template_utilities.go
  test/testlib/tls.go
Labels: meta

#147 Improve retention and handling of multiple files or folder in $NUODB_CRASHDIR
  stable/admin/files/nuoadmin
  stable/database/files/nuosm
  stable/database/files/nuote
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_crash_handling_test.go
  test/testlib/core_recovery.go
Labels: bug

#149 Add the ability to pass through custom annotations to be applied to pods
  stable/admin/README.md
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
  test/integration/template_admin_test.go
Labels: enhancement

#150 Start Kubernetes Aware Admin module with limited permissions
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_kaa_additions_test.go
  test/testlib/template_utilities.go
Labels: meta

#154 render --user option conditionally on a nun-null credentials
  stable/database/files/nuosm
Labels: bug
