Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-06, with the labels that each got.

#116 Clean out unused files
  images/Click-Personal-Access-Tokens.png
  images/Developer-Settings.png
  images/Generate-New-Token.png
  images/Generated-Token.png
  images/New-Personal-Access-Token.png
  images/Press-Generate-Token.png
  images/Select-Profile-Settings.png
  test/files/dashboard-adminuser.yaml
  test/files/role-tiller.yaml
  test/files/rolebinding-tiller.yaml
  test/files/ssh-agent.yaml
  test/lint_test.sh
  test/scripts/aws-mfa.sh
  test/scripts/delete.sh
  test/scripts/deploy.sh
  test/scripts/dockerlogin.sh
  test/scripts/functions.sh
  test/scripts/login.sh
  test/scripts/open.sh
  test/scripts/prepare.sh
  test/scripts/profile.sh
  test/scripts/purge.sh
  test/test_suite.sh
Labels: meta

#117 Jleslie/add new NuoDB logo
  README.md
  images/nuodb.svg
Labels: meta

#115 Add tests for future kubernetes-aware diagnostics
  test/files/nuodb-dump.json
  test/integration/kube_config_marshall_test.go
  test/minikube/minikube_domain_resync_test.go
  test/testlib/NuoDBKubeConfig.go
  test/testlib/minikube_utilities.go
Labels: feature, meta

#119 Add readiness probe timeouts in values
  stable/admin/README.md
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
Labels: enhancement

#120 Fix helm upgrade test
  test/testlib/minikube_utilities.go
Labels: meta

#121 Fix TLS rotation test
  test/testlib/tls.go
Labels: meta

#122 LB policy job affinity
  stable/admin/templates/job.yaml
Labels: enhancement

#123 Change initial backup policy from Never to OnFailure
  stable/database/templates/job.yaml
Labels: bug

#124 Fix killSM flaky test
  test/minikube/minikube_crash_handling_test.go
  test/testlib/minikube_utilities.go
Labels: meta
