Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-10, with the labels that each got.

#155 Remove https references for NUOCMD_API_SERVER and add certificates for upgrade tests
  stable/admin/templates/job.yaml
  stable/database/templates/job.yaml
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/tls.go
Labels: enhancement

#156 Move podAnnotations to create on the pod
  stable/admin/templates/statefulset.yaml
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/statefulset.yaml
  test/integration/template_admin_test.go
  test/integration/template_database_test.go
Labels: bug, enhancement

#157 remove single-quotes from curl_creds
  stable/database/files/nuosm
Labels: bug

#158 Change tests from assert to require
  go.mod
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_crash_handling_test.go
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_kaa_additions_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_test_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/minikube/verify_utility.go
  test/testlib/core_recovery.go
  test/testlib/minikube_utilities.go
  test/testlib/open_shift_utilities.go
  test/testlib/secrets.go
  test/testlib/tls.go
Labels: meta
