Repository nuodb/nuodb-helm-charts, pull requests merged in 2020-11, with the labels that each got.

#159 Test that KAA will not start if addRoleBinding is set to false
  test/minikube/minikube_kaa_additions_test.go
Labels: meta

#160 add timeout and retry on wait for starting SM
  stable/database/files/nuosm
Labels: bug

#161 Add NuoDB Collector support in NuoDB Helm charts
  go.sum
  stable/admin/README.md
  stable/admin/templates/_sidecar.tpl
  stable/admin/templates/nuocollector-configmap.yaml
  stable/admin/templates/role.yaml
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  stable/database/README.md
  stable/database/templates/_sidecar.tpl
  stable/database/templates/daemonset.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/nuocollector-configmap.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
  test/integration/template_collector_test.go
  test/minikube/minikube_base_collector_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: feature

#162 Change GoLang module to v3
  go.mod
  test/integration/database_marshall_test.go
  test/integration/kube_config_marshall_test.go
  test/integration/process_marshall_test.go
  test/integration/registry_entry_marshall_test.go
  test/integration/template_admin_test.go
  test/integration/template_collector_test.go
  test/integration/template_database_test.go
  test/integration/template_resources_test.go
  test/integration/template_storage_class_test.go
  test/integration/template_ycsb_test.go
  test/minikube/minikube_base_admin_test.go
  test/minikube/minikube_base_collector_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_base_thp_test.go
  test/minikube/minikube_crash_handling_test.go
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_e2e_demo_test.go
  test/minikube/minikube_kaa_additions_test.go
  test/minikube/minikube_long_admin_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_test_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/minikube/verify_utility.go
Labels: meta

#164 Support for installing YCSB from public charts repo
  scripts/ci/install_deps.sh
  test/testlib/nuodb_ycsb_utilities.go
Labels: meta
