Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-05, with the labels that each got.

#203 Updated Chart.yaml icon image references from nuodb.com to GitHub
  incubator/demo-ycsb/Chart.yaml
  stable/admin/Chart.yaml
  stable/database/Chart.yaml
  stable/restore/Chart.yaml
  stable/storage-class/Chart.yaml
  stable/transparent-hugepage/Chart.yaml
Labels: bug

#202 Validate restore source
  stable/database/files/nuosm
  stable/database/files/nuote
  stable/database/templates/_helpers.tpl
  stable/database/templates/configmap.yaml
  stable/restore/templates/_helpers.tpl
  test/integration/template_database_restore_test.go
  test/integration/template_restore_test.go
Labels: enhancement

#205 Fix hotCopy doc case
  docs/BackupAndRestore.md
  stable/database/README.md
Labels: documentation

#206 Minor doc fix
  stable/admin/README.md
  stable/database/README.md
  stable/restore/README.md
  stable/transparent-hugepage/README.md
Labels: documentation

#207 Bump NuoDB version to 4.2.1
  incubator/demo-ycsb/Chart.yaml
  stable/admin/Chart.yaml
  stable/admin/values.yaml
  stable/database/Chart.yaml
  stable/database/values.yaml
  stable/restore/Chart.yaml
  stable/restore/values.yaml
  stable/storage-class/Chart.yaml
  stable/transparent-hugepage/Chart.yaml
  test/minikube/minikube_base_admin_test.go
  test/minikube/minikube_rolling_upgrade_test.go
Labels: versioning

#209 Add 3.2.0 -> master upgrade test
  test/minikube/minikube_upgrade_helm_test.go
Labels: meta

#208 Skip test on NuoDB version
  go.mod
  go.sum
  test/minikube/minikube_long_restore_test.go
  test/testlib/nuodb_database_utilities.go
Labels: meta

#212 Change set of owners
  CODEOWNERS
Labels: meta

#211 Add troubleshooting section in B&R guide
  docs/BackupAndRestore.md
Labels: documentation

#214 [HELM-281] Recursively change permissions in init container
  stable/admin/templates/statefulset.yaml
  test/minikube/minikube_crash_handling_test.go
Labels: enhancement
