Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-04, with the labels that each got.

#196 Fix TestKubernetesUpgradeFullDatabaseMinorVersion test
  test/minikube/minikube_rolling_upgrade_test.go
Labels: meta

#195 Added stripLevels options in restore chart
  stable/restore/README.md
  stable/restore/files/nuorestore
  stable/restore/templates/job.yaml
  stable/restore/values.yaml
  test/integration/template_restore_test.go
  test/minikube/minikube_long_restore_test.go
  test/testlib/constants.go
  test/testlib/nuodb_database_utilities.go
Labels: bug

#197 Change the default timeout for all backup jobs
  go.mod
  go.sum
  stable/database/README.md
  stable/database/files/nuobackup
  stable/database/templates/cronjob.yaml
  stable/database/values.yaml
  test/integration/template_backup_test.go
  test/testlib/nuodb_database_utilities.go
Labels: enhancement

#200 Fix Backup&Restore nuodocker commands in the documentation
  docs/BackupAndRestore.md
Labels: documentation

#199 Add Helm YAML validation of autorestore type
  go.sum
  stable/database/templates/_helpers.tpl
  stable/database/templates/configmap.yaml
  test/integration/template_database_restore_test.go
Labels: enhancement
