Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-03, with the labels that each got.

#187 NuoDB Backup and Restore in Kubernetes (doc)
  docs/BackupAndRestore.md
Labels: documentation

#190 Add automated test and a HowTo document for HashiCorp vault
  docs/HowToHashiCorpVault.md
  docs/HowtoTLS.md
  scripts/ci/install_deps.sh
  stable/admin/values.yaml
  stable/database/values.yaml
  test/files/nuodb-policy.hcl
  test/files/vault-annotations-admin.yaml
  test/files/vault-annotations-database.yaml
  test/minikube/minikube_e2e_demo_test.go
  test/minikube/minikube_tls_admin_test.go
  test/testlib/constants.go
  test/testlib/hashicorp_utilities.go
Labels: documentation, meta

#189 Multi-cluster support in test framework
  .circleci/config.yml
  scripts/ci/install_deps.sh
  test/minikube/minikube_base_restore_test.go
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_long_restore_test.go
  test/multicluster/minikube_base_multicluster_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
  test/testlib/multicluster_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: meta

#188 Pod name should contain cluster name.
  stable/admin/templates/NOTES.txt
Labels: documentation

#192 Fix TestKubernetesAutoRestore random failures
  test/minikube/minikube_base_restore_test.go
Labels: meta

#194 Allow docker image overrides of upgrade tests
  test/minikube/minikube_rolling_upgrade_test.go
  test/testlib/constants.go
  test/testlib/minikube_utilities.go
Labels: meta
