Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-06, with the labels that each got.

#216 Fix comment string in nuosm
  stable/database/files/nuosm
Labels: meta

#217 Restarting SM fails if an AP is Disconnected
  stable/database/files/nuosm
  test/minikube/minikube_base_database_test.go
  test/testlib/NuoDBServer.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: bug

#219 Set evictUnknownProcesses=true in admin/values.yaml
  stable/admin/values.yaml
Labels: enhancement

#220 Rewrite upgrade database tests
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/nuodb_database_utilities.go
Labels: meta

#222 Remove option to start Storage Managers as DaemonSets
  stable/database/README.md
  stable/database/templates/daemonset.yaml
  stable/database/templates/statefulset.yaml
  stable/database/values.yaml
  test/integration/template_collector_test.go
  test/integration/template_database_test.go
  test/integration/template_resources_test.go
  test/minikube/minikube_base_collector_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_base_restore_test.go
Labels: removed

#223 Validate boolean helm variables
  stable/admin/templates/_helpers.tpl
  stable/admin/templates/_sidecar.tpl
  stable/admin/templates/job.yaml
  stable/admin/templates/nuocollector-configmap.yaml
  stable/admin/templates/service.yaml
  stable/admin/templates/statefulset.yaml
  stable/database/templates/_helpers.tpl
  stable/database/templates/_sidecar.tpl
  stable/database/templates/cronjob.yaml
  stable/database/templates/deployment.yaml
  stable/database/templates/nuocollector-configmap.yaml
  stable/database/templates/persistentvolumeclaim.yaml
  stable/database/templates/service-clusterip.yaml
  stable/database/templates/service-headless.yaml
  stable/database/templates/service.yaml
  stable/database/templates/statefulset.yaml
  test/files/database-journal-disabled.yaml
  test/integration/template_backup_test.go
Labels: bug
