Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-08, with the labels that each got.

#229 Bump the version of minikube in CircleCI tests from 1.2 to 1.22
  .circleci/config.yml
  scripts/ci/install_deps.sh
Labels: meta

#230 Bump the version of Helm in CircleCI tests from 3.2.4 to 3.6.3
  .circleci/config.yml
Labels: meta

#231 Bump version of GoTestSum in CircleCI tests from 0.6.0 to 1.7.0
  .circleci/config.yml
Labels: meta

#232 Rotating NuoDB TLS Certificates doc
  docs/HowToCertificatesRotation.md
Labels: documentation

#234 Change CircleCI environment to Kubernetes 1.21.3
  .circleci/config.yml
  scripts/ci/install_deps.sh
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_base_restore_test.go
  test/minikube/minikube_base_tde_test.go
  test/minikube/minikube_crash_handling_test.go
  test/minikube/minikube_domain_resync_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_tls_admin_test.go
  test/minikube/minikube_tls_rotation_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
  test/testlib/nuodb_database_utilities.go
Labels: meta

#237 Add HashiCorp Vault vs Kubernetes 1.21 bug workaround and documentation of disable_iss_validation=true
  .circleci/config.yml
  docs/HowToHashiCorpVault.md
  scripts/ci/install_deps.sh
  test/minikube/minikube_large_instance_test.go
  test/minikube/minikube_tls_admin_test.go
  test/testlib/hashicorp_utilities.go
Labels: documentation, meta

#235 Test failure: TestKubernetesStartDatabaseShrinkedAdmin
  .circleci/config.yml
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_domain_resync_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_admin_utilities.go
Labels: meta

#239 Add admin helm upgrade workaround to upgrade tests
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/minikube_utilities.go
  test/testlib/nuodb_database_utilities.go
  test/testlib/upgrade_utilities.go
Labels: meta

#240 Fix database restore with cold backup and external journal
  stable/database/files/nuosm
  test/minikube/minikube_base_restore_test.go
  test/minikube/minikube_long_restore_test.go
  test/testlib/nuodb_database_utilities.go
Labels: bug

#241 Fix comments on the doc after QA verification
  docs/HowToCertificatesRotation.md
Labels: documentation
