Repository nuodb/nuodb-helm-charts, pull requests merged in 2021-01, with the labels that each got.

#175 Remove leftover openshift flag
  stable/database/README-HOSTPATH.md
  stable/database/README.md
  stable/database/templates/secret.yaml
  stable/database/values.yaml
Labels: removed

#177 Make LB job optional
  stable/admin/README.md
  stable/admin/templates/job.yaml
  stable/admin/values.yaml
  test/integration/template_admin_test.go
  test/integration/template_resources_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/minikube/verify_utility.go
Labels: deprecated

#178 Remove database name check after restore
  stable/database/files/nuosm
Labels: meta

#176 Fix for marking restore as successful
  stable/database/files/nuosm
Labels: bug

#180 Add evicted-servers to admin statefulset
  stable/admin/README.md
  stable/admin/templates/_helpers.tpl
  stable/admin/templates/statefulset.yaml
  stable/admin/values.yaml
  test/integration/template_admin_test.go
Labels: enhancement, feature

#179 Kubernetes Jobs cause rolling upgrade errors
  go.sum
  stable/database/files/nuobackup
  stable/database/templates/cronjob.yaml
  stable/database/templates/job.yaml
  test/integration/template_resources_test.go
  test/minikube/minikube_base_database_test.go
  test/minikube/minikube_rolling_upgrade_test.go
  test/minikube/minikube_upgrade_helm_test.go
  test/testlib/minikube_utilities.go
Labels: enhancement
